import os
import re

files = [
    "frontend/src/types/assistant.ts",
    "frontend/src/types/api-key.ts",
    "frontend/src/types/cost.ts",
    "frontend/src/types/project.ts",
    "frontend/src/api.ts",
    "frontend/src/index.css",
    "frontend/src/components/layout/AssetSidebar.tsx",
    "frontend/src/components/layout/ExportScopeDialog.tsx",
    "frontend/src/components/layout/ToastOverlay.tsx",
    "frontend/src/components/layout/GlobalHeader.test.tsx",
    "frontend/src/components/layout/StudioLayout.tsx",
    "frontend/src/components/layout/WorkspaceNotificationsDrawer.tsx",
    "frontend/src/components/layout/UsageDrawer.tsx",
    "frontend/src/components/ui/ClueStack.tsx",
    "frontend/src/components/ui/GenerateButton.tsx",
    "frontend/src/components/ui/Popover.tsx",
    "frontend/src/components/ui/AvatarStack.tsx",
    "frontend/src/components/ui/ImageLightbox.tsx",
    "frontend/src/components/ui/ProviderModelSelect.tsx",
    "frontend/src/components/ui/PreviewableImageFrame.tsx",
    "frontend/src/components/ui/PreviewableImageFrame.test.tsx",
    "frontend/src/components/ui/ImageFlipReveal.tsx",
    "frontend/src/components/ui/ProviderIcon.tsx",
    "frontend/src/components/copilot/SlashCommandMenu.test.tsx",
    "frontend/src/components/copilot/SlashCommandMenu.tsx",
    "frontend/src/components/copilot/AgentCopilot.tsx",
    "frontend/src/components/copilot/AgentCopilot.test.tsx",
    "frontend/src/components/copilot/PendingQuestionWizard.test.tsx",
    "frontend/src/components/copilot/TodoListPanel.tsx",
    "frontend/src/components/copilot/ContextBanner.tsx",
    "frontend/src/components/copilot/pending-question.ts",
    "frontend/src/components/copilot/PendingQuestionWizard.tsx",
    "frontend/src/components/copilot/chat/ThinkingBlock.tsx",
    "frontend/src/components/copilot/chat/TaskProgressBlock.tsx",
    "frontend/src/components/copilot/chat/ToolCallWithResult.tsx",
    "frontend/src/components/copilot/chat/utils.ts",
    "frontend/src/components/copilot/chat/ContentBlockRenderer.tsx",
    "frontend/src/components/copilot/chat/SkillContentBlock.tsx",
    "frontend/src/components/copilot/chat/ToolCallWithResult.test.tsx",
    "frontend/src/components/copilot/TodoListPanel.test.tsx",
    "frontend/src/components/shared/ArchiveDiagnosticsDialog.tsx",
    "frontend/src/components/canvas/OverviewCanvas.tsx",
    "frontend/src/components/canvas/WelcomeCanvas.tsx",
    "frontend/src/components/canvas/lorebook/ClueCard.tsx",
    "frontend/src/components/canvas/lorebook/LorebookGallery.tsx",
    "frontend/src/components/canvas/lorebook/CharacterCard.test.tsx",
    "frontend/src/components/canvas/lorebook/AddCharacterForm.tsx",
    "frontend/src/components/canvas/lorebook/CharacterCard.tsx",
    "frontend/src/components/canvas/lorebook/AddCharacterForm.test.tsx",
    "frontend/src/components/canvas/lorebook/AddClueForm.tsx",
    "frontend/src/components/canvas/timeline/SegmentCard.test.tsx",
    "frontend/src/components/canvas/timeline/DialogueListEditor.tsx",
    "frontend/src/components/canvas/timeline/SegmentCard.tsx",
    "frontend/src/components/canvas/timeline/VideoPromptEditor.tsx",
    "frontend/src/components/canvas/timeline/VersionTimeMachine.test.tsx",
    "frontend/src/components/canvas/timeline/PreprocessingView.tsx",
    "frontend/src/components/canvas/timeline/VersionTimeMachine.tsx",
    "frontend/src/components/canvas/timeline/TimelineCanvas.tsx",
    "frontend/src/components/canvas/timeline/ImagePromptEditor.tsx",
    "frontend/src/components/canvas/StudioCanvasRouter.tsx",
    "frontend/src/components/canvas/SourceFileViewer.tsx",
    "frontend/src/components/canvas/WelcomeCanvas.test.tsx",
    "frontend/src/components/canvas/StudioCanvasRouter.test.tsx",
    "frontend/src/components/canvas/OverviewCanvas.test.tsx",
    "frontend/src/components/task-hud/TaskHud.tsx",
    "frontend/src/components/pages/ProviderDetail.tsx",
    "frontend/src/components/pages/settings/MediaModelSection.tsx",
    "frontend/src/components/pages/settings/UsageStatsSection.tsx",
    "frontend/src/components/pages/settings/CustomProviderDetail.tsx",
    "frontend/src/components/pages/settings/CustomProviderForm.tsx",
    "frontend/src/components/pages/settings/CustomProviderSection.tsx",
    "frontend/src/components/pages/OpenClawModal.tsx",
    "frontend/src/components/pages/CredentialList.tsx",
    "frontend/src/components/pages/TabSaveFooter.tsx",
    "frontend/src/components/pages/CreateProjectModal.test.tsx",
    "frontend/src/components/pages/SystemConfigPage.test.tsx",
    "frontend/src/components/pages/ProjectsPage.test.tsx",
    "frontend/src/router.tsx",
    "frontend/src/stores/config-status-store.ts",
    "frontend/src/stores/stores.test.ts",
    "frontend/src/stores/cost-store.ts",
    "frontend/src/utils/project-changes.test.ts",
    "frontend/src/utils/project-changes.ts",
    "frontend/src/hooks/useProjectEventsSSE.test.tsx",
    "frontend/src/hooks/useAssistantSession.test.tsx",
    "frontend/src/hooks/useScrollTarget.ts",
    "frontend/src/hooks/useTasksSSE.ts",
    "frontend/src/hooks/useWarnUnsaved.ts",
    "frontend/src/hooks/useProjectEventsSSE.ts",
    "frontend/src/css/studio.css",
    "frontend/src/css/styles.css",
    "frontend/src/api.test.ts",
    "frontend/src/router.test.tsx",
    "frontend/src/pages/NotFoundPage.tsx"
]

chinese_char_pattern = re.compile(r'[\u4e00-\u9fff]')

results = []
for file_path in files:
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            for i, line in enumerate(f, 1):
                if chinese_char_pattern.search(line):
                    results.append(f"{file_path}:{i}:{line.strip()}")

for r in results:
    print(r)
