import os
import re

# Mapping of Chinese strings to Indonesian
# Sorted by length (descending) automatically in the script logic to avoid partial replacements.
mapping = {
    "认证已过期，请重新登录": "Sesi berakhir, silakan login kembali",
    "项目创建后不支持修改 content_mode": "Mode konten tidak dapat diubah setelah proyek dibuat",
    "确定要删除 \"${filename}\" 吗？": "Yakin ingin menghapus \"${filename}\"?",
    "确定要删除这个会话吗？": "Yakin ingin menghapus sesi ini?",
    "有未保存的更改": "Ada perubahan yang belum disimpan",
    "页面未找到": "Halaman tidak ditemukan",
    "返回首页": "Kembali ke Beranda",
    "加载中…": "Memuat...",
    "加载中": "Memuat",
    "加载项目数据中": "Memuat data proyek",
    "暂无项目": "Belum ada proyek",
    "暂无数据": "Belum ada data",
    "暂无剧集": "Belum ada episode",
    "暂无分镜": "Belum ada storyboard",
    "暂无角色": "Belum ada karakter",
    "暂无线索": "Belum ada petunjuk",
    "暂无源文件": "Belum ada file sumber",
    "暂无文件": "Belum ada file",
    "暂无历史版本": "Belum ada riwayat versi",
    "暂无调用记录": "Belum ada riwayat panggilan",
    "暂无对话": "Belum ada percakapan",
    "暂无通知": "Belum ada notifikasi",
    "暂无预处理内容": "Belum ada konten pra-pemrosesan",
    "暂无密钥": "Belum ada kunci",
    "上传失败": "Gagal mengunggah",
    "上传成功": "Berhasil mengunggah",
    "上传中": "Mengunggah",
    "保存中…": "Menyimpan...",
    "保存中": "Menyimpan",
    "保存失败": "Gagal menyimpan",
    "保存成功": "Berhasil menyimpan",
    "保存": "Simpan",
    "删除失败": "Gagal menghapus",
    "删除成功": "Berhasil menghapus",
    "删除中": "Menghapus",
    "删除": "Hapus",
    "更新失败": "Gagal memperbarui",
    "更新成功": "Berhasil memperbarui",
    "更新": "Perbarui",
    "编辑": "Edit",
    "修改": "Ubah",
    "新建项目": "Proyek Baru",
    "创建项目": "Buat Proyek",
    "新建会话": "Sesi Baru",
    "新建或更新": "Buat atau Perbarui",
    "确认删除": "Konfirmasi Hapus",
    "确认取消": "Konfirmasi Batal",
    "确认清除": "Konfirmasi Hapus",
    "确认": "Konfirmasi",
    "取消": "Batal",
    "确定": "OK",
    "成功": "Berhasil",
    "失败": "Gagal",
    "错误": "Kesalahan",
    "导入失败": "Gagal mengimpor",
    "导入成功": "Berhasil mengimpor",
    "导入包校验失败": "Validasi paket impor gagal",
    "导入警告": "Peringatan impor",
    "导入诊断": "Diagnostik impor",
    "导出失败": "Gagal mengekspor",
    "导出成功": "Berhasil mengekspor",
    "导出": "Ekspor",
    "获取模型列表失败": "Gagal mendapatkan daftar model",
    "获取文件内容失败": "Gagal mendapatkan isi file",
    "连接测试失败": "Uji koneksi gagal",
    "测试连接": "Uji Koneksi",
    "测试中…": "Menguji...",
    "连接中…": "Menghubungkan...",
    "已连接": "Terhubung",
    "未配置": "Belum dikonfigurasi",
    "未设置": "Belum diatur",
    "请输入": "Silakan masukkan",
    "请填写": "Silakan isi",
    "请选择": "Silakan pilih",
    "搜索模型…": "Cari model...",
    "搜索": "Cari",
    "点击放大图片": "Klik untuk memperbesar gambar",
    "关闭全屏预览": "Tutup pratinjau layar penuh",
    "全屏预览": "Pratinjau layar penuh",
    "系统配置与 API 访问管理": "Konfigurasi Sistem & Manajemen Akses API",
    "系统配置": "Konfigurasi Sistem",
    "项目管理": "Manajemen Proyek",
    "角色管理": "Manajemen Karakter",
    "线索管理": "Manajemen Petunjuk",
    "文件管理": "Manajemen File",
    "版本管理": "Manajemen Versi",
    "费用明细": "Detail Biaya",
    "用量统计": "Statistik Penggunaan",
    "API 管理": "Manajemen API",
    "密钥管理": "Manajemen Kunci",
    "凭证管理": "Manajemen Kredensial",
    "供应商": "Provider",
    "自定义供应商": "Provider Kustom",
    "文本生成": "Generasi Teks",
    "图片生成": "Generasi Gambar",
    "视频生成": "Generasi Video",
    "智能体": "Agen AI",
    "分镜图": "Storyboard",
    "剧本": "Skenario",
    "剧集": "Episode",
    "第一集": "Episode 1",
    "当前会话": "Sesi saat ini",
    "历史版本": "Riwayat Versi",
    "版本": "Versi",
    "还原到指定版本": "Pulihkan ke versi tertentu",
    "确定还原到此版本吗？": "Yakin ingin memulihkan ke versi ini?",
    "还原中…": "Memulihkan...",
    "还原失败": "Gagal memulihkan",
    "还原成功": "Berhasil memulihkan",
    "确定要删除 \"${filename}\" 吗？": "Yakin ingin menghapus \"${filename}\"?",
    "确定要删除这个会话吗": "Yakin ingin menghapus sesi ini?",
    "确定取消所有排队中的任务吗？": "Yakin ingin membatalkan semua tugas dalam antrean?",
    "确定取消此任务吗？": "Yakin ingin membatalkan tugas ini?",
    "取消此任务将同时取消其依赖的所有任务。": "Membatalkan tugas ini juga akan membatalkan semua tugas dependennya.",
    "任务队列": "Antrean Tugas",
    "任务清单": "Daftar Tugas",
    "运行中": "Berjalan",
    "排队中": "Dalam antrean",
    "已完成": "Selesai",
    "已取消": "Dibatalkan",
    "执行失败": "Gagal dieksekusi",
    "生成中": "Menghasilkan",
    "解析数据失败": "Gagal mengurai data",
    "同步项目变更失败": "Gagal menyinkronkan perubahan proyek",
    "未找到可定位的内容": "Konten tidak ditemukan",
    "工作台": "Studio",
    "项目概览": "Ikhtisar Proyek",
    "源文件": "File Sumber",
    "上传源文件": "Unggah File Sumber",
    "剧本文件名": "Nama File Skenario",
    "角色名称": "Nama Karakter",
    "线索名称": "Nama Petunjuk",
    "输入角色描述": "Masukkan deskripsi karakter",
    "输入线索描述": "Masukkan deskripsi petunjuk",
    "输入消息": "Ketik pesan",
    "思考中…": "Berpikir...",
    "回答失败": "Gagal menjawab",
    "发送失败": "Gagal mengirim",
    "已复制": "Berhasil disalin",
    "复制": "Salin",
    "名称": "Nama",
    "描述": "Deskripsi",
    "类型": "Tipe",
    "状态": "Status",
    "价格": "Harga",
    "余额": "Saldo",
    "支出": "Pengeluaran",
    "总计": "Total",
    "详情": "Detail",
    "操作": "Aksi",
    "默认": "Default",
    "启用": "Aktifkan",
    "禁用": "Nonaktifkan",
    "已启用": "Diaktifkan",
    "已禁用": "Dinonaktifkan",
    "添加": "Tambah",
    "完成": "Selesai",
    "继续": "Lanjut",
    "撤销": "Urungkan",
    "重试": "Coba lagi",
    "刷新": "Segarkan",
    "返回": "Kembali",
    "隐藏": "Sembunyikan",
    "显示": "Tampilkan",
    "展开": "Buka",
    "收起": "Tutup",
    "全部": "Semua",
    "选项": "Opsi",
    "自动": "Otomatis",
    "手动": "Manual",
    "预览": "Pratinjau",
    "下载": "Unduh",
    "风格": "Gaya",
    "材质": "Material",
    "镜头": "Kamera",
    "构图": "Komposisi",
    "光线": "Cahaya",
    "色彩": "Warna",
    "环境": "Lingkungan",
    "氛围": "Atmosfer",
    "动作": "Aksi",
    "表情": "Ekspresi",
    "外貌": "Penampilan",
    "性格": "Kepribadian",
    "重要性": "Kepentingan",
    "提示词": "Prompt",
    "分镜描述": "Deskripsi Storyboard",
    "角色描述": "Deskripsi Karakter",
    "线索描述": "Deskripsi Petunjuk",
    "环境音效": "Efek Suara Lingkungan",
    "音效": "Efek Suara",
    "镜头运动": "Gerakan Kamera",
    "镜头语言": "Bahasa Kamera",
    "画面模式": "Mode Gambar",
    "比例": "Rasio",
    "时长": "Durasi",
    "秒": "detik",
    "分钟": "menit",
    "刚刚": "baru saja",
    "分钟前": "menit yang lalu",
    "小时前": "jam yang lalu",
    "昨天": "kemarin",
    "前天": "dua hari yang lalu",
    "已读": "Sudah dibaca",
    "未读": "Belum dibaca",
    "新通知": "Notifikasi Baru",
    "任务清单已更新": "Daftar tugas diperbarui",
    "AI 刚更新了": "AI baru saja memperbarui",
    "AI 刚新增了": "AI baru saja menambahkan",
    "AI 刚删除了": "AI baru saja menghapus",
    "AI 刚生成了": "AI baru saja menghasilkan",
    "点击查看": "Klik untuk melihat",
    "已生成": "Telah dihasilkan",
    "已更新": "Telah diperbarui",
    "已创建": "Telah dibuat",
    "已删除": "Telah dihapus",
    "的视频已生成": " video telah dihasilkan",
    "的分镜图已生成": " storyboard telah dihasilkan",
    "的分镜图": " storyboard",
    "的视频": " video",
    "个角色": " karakter",
    "个线索": " petunjuk",
    "个片段": " segmen",
    "个任务": " tugas",
    "个项目": " proyek",
    "个集": " episode",
    "暂无": "Belum ada ",
    "角色「${name}」": "Karakter \"${name}\"",
    "线索「${name}」": "Petunjuk \"${name}\"",
    "分镜「${name}」": "Storyboard \"${name}\"",
    "项目「${name}」": "Proyek \"${name}\"",
    "剧集「${name}」": "Episode \"${name}\"",
    "导入包校验中...": "Memvalidasi paket impor...",
    "检测到项目编号重复": "ID Proyek duplikat terdeteksi",
    "自动重命名导入": "Impor dengan nama baru otomatis",
    "手动重命名": "Ubah nama manual",
    "页面未找到": "Halaman tidak ditemukan",
    "返回首页": "Kembali ke Beranda",
    "设置": "Pengaturan",
    "系统配置与 API 访问管理": "Konfigurasi Sistem & Manajemen Akses API",
    "角色参考图预览": "Pratinjau referensi karakter",
    "重新生成设计图": "Generate ulang desain",
    "保存文件失败": "Gagal menyimpan file",
    "删除文件失败": "Gagal menghapus file",
    "上传失败": "Gagal mengunggah",
    "上传成功": "Berhasil mengunggah",
    "上传参考图片": "Unggah gambar referensi",
    "上传风格参考图": "Unggah referensi gaya",
    "风格描述已保存": "Deskripsi gaya disimpan",
    "风格描述用于补充视觉规则": "Deskripsi gaya digunakan untuk aturan visual",
    "参考图会参与后续画面生成": "Gambar referensi akan digunakan untuk generasi berikutnya",
    "材质与镜头语言": "Material & Bahasa Kamera",
    "说书模式": "Mode Storytelling",
    "剧本生成": "Generasi Skenario",
    "分镜生成": "Generasi Storyboard",
    "视频创作": "Kreasi Video",
    "向你的 OpenClaw 发送上述提示词": "Kirim prompt di atas ke OpenClaw Anda",
    "复制提示词，粘贴给 OpenClaw 发送": "Salin prompt, tempel dan kirim ke OpenClaw",
    "OpenClaw 从 Skill 文档学习能力": "OpenClaw mempelajari kemampuan dari dokumen Skill",
    "OpenClaw 会自动读取 ArcReel Skill 文档": "OpenClaw akan membaca dokumen Skill ArcReel secara otomatis",
    "OpenClaw 与 ArcReel 交互并创建视频": "OpenClaw berinteraksi dengan ArcReel untuk membuat video",
    "描述你的创作需求，OpenClaw 将调用 ArcReel 完成项目管理、剧本生成和视频创作": "Deskripsikan kebutuhan kreatif Anda, OpenClaw akan memanggil ArcReel untuk manajemen proyek, skenario, dan video",
    "学习 ${skillUrl} 然后遵循 skill，了解如何使用 ArcReel 创作视频": "Pelajari ${skillUrl} lalu ikuti skill untuk mengetahui cara menggunakan ArcReel",
    "OpenClaw 集成指南": "Panduan Integrasi OpenClaw",
    "将 ArcReel 接入 OpenClaw AI Agent": "Hubungkan ArcReel ke Agen AI OpenClaw",
    "获取 API 令牌": "Dapatkan Token API",
    "API Key（列表展示用，不含完整 key）。": "Metadata API Key (untuk daftar, tidak termasuk kunci lengkap).",
    "创建 API Key 的响应（含完整 key，仅在创建时出现）。": "Respons pembuatan API Key (termasuk kunci lengkap, hanya muncul saat dibuat).",
    "费用明细：货币 → 金额 映射": "Detail biaya: Mata uang → Pemetaan jumlah",
    "按类型拆分的费用": "Biaya berdasarkan tipe",
    "单个 segment 的费用": "Biaya per segmen",
    "单集费用": "Biaya per episode",
    "模型信息": "Informasi Model",
    "费用估算 API 响应": "Respons API estimasi biaya",
    "项目创建后不支持修改 content_mode": "Mode konten tidak dapat diubah setelah proyek dibuat",
    "构造剪映草稿下载 URL": "Membangun URL unduhan draf Jianying",
    "检查 fetch 响应状态，抛出包含后端错误信息的 Error。": "Periksa status respons fetch, lempar Error dengan informasi kesalahan backend.",
    "用于不经过 API.request() 的自定义 fetch 调用。": "Digunakan untuk panggilan fetch kustom tanpa melalui API.request().",
    "为 fetch options 注入 Authorization header": "Suntikkan header Authorization ke opsi fetch",
    "为 URL 追加 token query param（用于 EventSource）": "Tambahkan parameter query token ke URL (untuk EventSource)",
    "通用请求方法": "Metode permintaan umum",
    "上传凭证失败": "Gagal mengunggah kredensial",
    "获取按 provider 分组的用量统计。": "Dapatkan statistik penggunaan yang dikelompokkan berdasarkan provider.",
    "获取项目费用估算。": "Dapatkan estimasi biaya proyek.",
    "项目概览": "Ikhtisar Proyek",
    "源文件列表": "Daftar File Sumber",
    "上传源文件": "Unggah File Sumber",
    "删除文件": "Hapus File",
    "确定要删除 \"${filename}\" 吗？": "Yakin ingin menghapus \"${filename}\"?",
    "暂无文件": "Belum ada file",
    "项目概览": "Ikhtisar Proyek",
    "导出当前项目": "Ekspor Proyek Saat Ini",
    "选择导出范围": "Pilih Jangkauan Ekspor",
    "全部 (项目 + 脚本 + 媒体)": "Semua (Proyek + Skenario + Media)",
    "脚本 + 媒体 (体积更小)": "Skenario + Media (Ukuran lebih kecil)",
    "仅脚本 (JSON)": "Hanya Skenario (JSON)",
    "导出为剪映草稿": "Ekspor sebagai Draf Jianying",
    "下载草稿": "Unduh Draf",
    "准备中...": "Menyiapkan...",
    "导出失败": "Ekspor Gagal",
    "成功率": "Tingkat Keberhasilan",
    "类型: 文本生成": "Tipe: Generasi Teks",
    "时长": "Durasi",
    "API 格式": "Format API",
    "创建时间": "Waktu Pembuatan",
    "模型列表": "Daftar Model",
    "已连接": "Terhubung",
    "未配置": "Belum dikonfigurasi",
    "编辑自定义供应商": "Edit Provider Kustom",
    "添加自定义供应商": "Tambah Provider Kustom",
    "名称": "Nama",
    "供应商名称": "Nama Provider",
    "获取模型列表": "Dapatkan Daftar Model",
    "启用模型": "Aktifkan Model",
    "默认": "Default",
    "币种": "Mata uang",
    "输入价格": "Harga Input",
    "输出价格": "Harga Output",
    "手动添加模型": "Tambah Model Manual",
    "保存中...": "Menyimpan...",
    "测试中...": "Menguji...",
    "有未保存的更改": "Ada perubahan yang belum disimpan",
    "撤销": "Urungkan",
    "保存": "Simpan",
    "演示项目": "Proyek Demo",
    "创建项目": "Buat Proyek",
    "例如：重生之皇后威武": "Contoh: Rebirth of the Empress",
    "系统配置与 API 访问管理": "Konfigurasi Sistem & Manajemen Akses API",
    "以下必填配置尚未完成：": "Konfigurasi wajib berikut belum lengkap:",
    "返回项目大厅": "Kembali ke Beranda Proyek",
    "加载项目列表...": "Memuat daftar proyek...",
    "暂无项目": "Belum ada proyek",
    "点击右上角「新建项目」或「导入 ZIP」开始创作": "Klik \"Proyek Baru\" atau \"Impor ZIP\" untuk mulai berkreasi",
    "发现未识别的附加文件/目录": "File/direktori tambahan tidak dikenal terdeteksi",
    "补全缺失字段": "Lengkapi field yang hilang",
    "导入警告": "Peringatan Impor",
    "缺少 project.json": "Kehilangan project.json",
    "项目编号已存在": "ID Proyek sudah ada",
    "检测到项目编号重复": "ID Proyek duplikat terdeteksi",
    "自动重命名导入": "Impor dengan nama baru otomatis",
    "页面未找到": "Halaman tidak ditemukan",
    "返回首页": "Kembali ke Beranda",
    "分镜图": "Storyboard",
    "视频": "Video",
    "角色": "Karakter",
    "线索": "Petunjuk",
    "分镜": "Storyboard",
    "剧集": "Episode",
    "项目概览": "Ikhtisar Proyek",
    "预处理": "Pra-pemrosesan",
    "内容": "Konten",
    "AI 刚生成了": "AI baru saja menghasilkan",
    "AI 刚新增了": "AI baru saja menambahkan",
    "AI 刚删除了": "AI baru saja menghapus",
    "AI 刚更新了": "AI baru saja memperbarui",
    "的分镜图已生成": " storyboard telah dihasilkan",
    "的视频已生成": " video telah dihasilkan",
    "已创建": "Telah dibuat",
    "已删除": "Telah dihapus",
    "已更新": "Telah diperbarui",
    "已生成 ${count} 个": "Telah dihasilkan ${count} ",
    "新增了 ${count} 个": "Ditambahkan ${count} ",
    "删除了 ${count} 个": "Dihapus ${count} ",
    "更新了 ${count} 个": "Diperbarui ${count} ",
    "点击查看": "Klik untuk melihat",
    "第一集": "Episode 1",
    "勇者": "Pahlawan",
    "线索「玉佩」": "Petunjuk \"Jade Pendant\"",
    "角色「hero」": "Karakter \"hero\"",
    "分镜「E1S01」": "Storyboard \"E1S01\"",
    "输出": "Output",
    "摘要": "Ringkasan",
    "详细": "Detail",
    "简洁输出": "Output ringkas",
    "完整说明": "Penjelasan lengkap",
    "回答失败": "Gagal menjawab",
    "发送失败": "Gagal mengirim",
    "未找到可定位的内容": "Konten tidak ditemukan",
    "同步项目变更失败": "Gagal menyinkronkan perubahan proyek",
    "工作台主题色": "Warna tema Studio",
    "字体定义": "Definisi Font",
    "统一焦点指示": "Indikator fokus seragam",
    "强调色": "Warna aksen",
    "片段卡片": "Kartu segmen",
    "呼吸灯动画": "Animasi pernapasan",
    "滚动条样式": "Gaya scrollbar",
    "卡片悬停效果": "Efek hover kartu",
    "模态框动画": "Animasi modal",
    "Tab 激活状态": "Status aktif Tab",
    "文件拖拽区域": "Area tarik file",
    "图片预览": "Pratinjau gambar",
    "视频预览": "Pratinjau video",
    "进度环": "Cincin progres",
    "响应式调整": "Penyesuaian responsif",
    "角色「张三」": "Karakter \"Zhang San\"",
    "角色「李四」": "Karakter \"Li Si\"",
    "角色「王五」": "Karakter \"Wang Wu\"",
    "角色「赵六」": "Karakter \"Zhao Liu\"",
    "角色「钱七」": "Karakter \"Qian Qi\"",
    "角色「孙八」": "Karakter \"Sun Ba\"",
    "线索「玉佩」": "Petunjuk \"Jade Pendant\"",
    "角色「hero」": "Karakter \"hero\"",
    "角色「mage」": "Karakter \"mage\"",
}

files = [
    "frontend/src/types/assistant.ts", "frontend/src/types/api-key.ts", "frontend/src/types/cost.ts",
    "frontend/src/types/project.ts", "frontend/src/api.ts", "frontend/src/index.css",
    "frontend/src/components/layout/AssetSidebar.tsx", "frontend/src/components/layout/ExportScopeDialog.tsx",
    "frontend/src/components/layout/ToastOverlay.tsx", "frontend/src/components/layout/GlobalHeader.test.tsx",
    "frontend/src/components/layout/StudioLayout.tsx", "frontend/src/components/layout/WorkspaceNotificationsDrawer.tsx",
    "frontend/src/components/layout/UsageDrawer.tsx", "frontend/src/components/ui/ClueStack.tsx",
    "frontend/src/components/ui/GenerateButton.tsx", "frontend/src/components/ui/Popover.tsx",
    "frontend/src/components/ui/AvatarStack.tsx", "frontend/src/components/ui/ImageLightbox.tsx",
    "frontend/src/components/ui/ProviderModelSelect.tsx", "frontend/src/components/ui/PreviewableImageFrame.tsx",
    "frontend/src/components/ui/PreviewableImageFrame.test.tsx", "frontend/src/components/ui/ImageFlipReveal.tsx",
    "frontend/src/components/ui/ProviderIcon.tsx", "frontend/src/components/copilot/SlashCommandMenu.test.tsx",
    "frontend/src/components/copilot/SlashCommandMenu.tsx", "frontend/src/components/copilot/AgentCopilot.tsx",
    "frontend/src/components/copilot/AgentCopilot.test.tsx", "frontend/src/components/copilot/PendingQuestionWizard.test.tsx",
    "frontend/src/components/copilot/TodoListPanel.tsx", "frontend/src/components/copilot/ContextBanner.tsx",
    "frontend/src/components/copilot/pending-question.ts", "frontend/src/components/copilot/PendingQuestionWizard.tsx",
    "frontend/src/components/copilot/chat/ThinkingBlock.tsx", "frontend/src/components/copilot/chat/TaskProgressBlock.tsx",
    "frontend/src/components/copilot/chat/ToolCallWithResult.tsx", "frontend/src/components/copilot/chat/utils.ts",
    "frontend/src/components/copilot/chat/ContentBlockRenderer.tsx", "frontend/src/components/copilot/chat/SkillContentBlock.tsx",
    "frontend/src/components/copilot/chat/ToolCallWithResult.test.tsx", "frontend/src/components/copilot/TodoListPanel.test.tsx",
    "frontend/src/components/shared/ArchiveDiagnosticsDialog.tsx", "frontend/src/components/canvas/OverviewCanvas.tsx",
    "frontend/src/components/canvas/WelcomeCanvas.tsx", "frontend/src/components/canvas/lorebook/ClueCard.tsx",
    "frontend/src/components/canvas/lorebook/LorebookGallery.tsx", "frontend/src/components/canvas/lorebook/CharacterCard.test.tsx",
    "frontend/src/components/canvas/lorebook/AddCharacterForm.tsx", "frontend/src/components/canvas/lorebook/CharacterCard.tsx",
    "frontend/src/components/canvas/lorebook/AddCharacterForm.test.tsx", "frontend/src/components/canvas/lorebook/AddClueForm.tsx",
    "frontend/src/components/canvas/timeline/SegmentCard.test.tsx", "frontend/src/components/canvas/timeline/DialogueListEditor.tsx",
    "frontend/src/components/canvas/timeline/SegmentCard.tsx", "frontend/src/components/canvas/timeline/VideoPromptEditor.tsx",
    "frontend/src/components/canvas/timeline/VersionTimeMachine.test.tsx", "frontend/src/components/canvas/timeline/PreprocessingView.tsx",
    "frontend/src/components/canvas/timeline/VersionTimeMachine.tsx", "frontend/src/components/canvas/timeline/TimelineCanvas.tsx",
    "frontend/src/components/canvas/timeline/ImagePromptEditor.tsx", "frontend/src/components/canvas/StudioCanvasRouter.tsx",
    "frontend/src/components/canvas/SourceFileViewer.tsx", "frontend/src/components/canvas/WelcomeCanvas.test.tsx",
    "frontend/src/components/canvas/StudioCanvasRouter.test.tsx", "frontend/src/components/canvas/OverviewCanvas.test.tsx",
    "frontend/src/components/task-hud/TaskHud.tsx", "frontend/src/components/pages/ProviderDetail.tsx",
    "frontend/src/components/pages/settings/MediaModelSection.tsx", "frontend/src/components/pages/settings/UsageStatsSection.tsx",
    "frontend/src/components/pages/settings/CustomProviderDetail.tsx", "frontend/src/components/pages/settings/CustomProviderForm.tsx",
    "frontend/src/components/pages/settings/CustomProviderSection.tsx", "frontend/src/components/pages/OpenClawModal.tsx",
    "frontend/src/components/pages/CredentialList.tsx", "frontend/src/components/pages/TabSaveFooter.tsx",
    "frontend/src/components/pages/CreateProjectModal.test.tsx", "frontend/src/components/pages/SystemConfigPage.test.tsx",
    "frontend/src/components/pages/ProjectsPage.test.tsx", "frontend/src/router.tsx",
    "frontend/src/stores/config-status-store.ts", "frontend/src/stores/stores.test.ts",
    "frontend/src/stores/cost-store.ts", "frontend/src/utils/project-changes.test.ts",
    "frontend/src/utils/project-changes.ts", "frontend/src/hooks/useProjectEventsSSE.test.tsx",
    "frontend/src/hooks/useAssistantSession.test.tsx", "frontend/src/hooks/useScrollTarget.ts",
    "frontend/src/hooks/useTasksSSE.ts", "frontend/src/hooks/useWarnUnsaved.ts",
    "frontend/src/hooks/useProjectEventsSSE.ts", "frontend/src/css/studio.css",
    "frontend/src/css/styles.css", "frontend/src/api.test.ts",
    "frontend/src/router.test.tsx", "frontend/src/pages/NotFoundPage.tsx"
]

# Add many more specific translations for shorter terms if needed
# Sort mapping by length descending to avoid partial replacements
sorted_keys = sorted(mapping.keys(), key=len, reverse=True)

# Also handle general Chinese characters that might be missed
# but we prefer exact string replacements for accuracy.

for file_path in files:
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
        
        original_content = content
        for key in sorted_keys:
            # Simple string replacement
            content = content.replace(key, mapping[key])
        
        # Also try to catch remaining Chinese characters with a simple heuristic or generic translations
        # for things like "角色", "线索" if they appear outside the mapping
        generic_mapping = {
            "角色": "Karakter",
            "线索": "Petunjuk",
            "分镜": "Storyboard",
            "项目": "Proyek",
            "成功": "Berhasil",
            "失败": "Gagal",
            "保存": "Simpan",
            "删除": "Hapus",
            "编辑": "Edit",
            "取消": "Batal",
            "确认": "Konfirmasi",
            "导入": "Impor",
            "导出": "Ekspor",
            "上传": "Unggah",
            "下载": "Unduh",
            "视频": "Video",
            "图片": "Gambar",
            "文本": "Teks",
            "剧本": "Skenario",
            "剧集": "Episode",
            "暂无": "Belum ada",
            "加载中": "Memuat",
            "新建": "Buat baru",
            "创作": "Kreasi",
            "生成": "Generate",
            "描述": "Deskripsi",
            "名称": "Nama",
            "价格": "Harga",
            "类型": "Tipe",
            "状态": "Status",
            "设置": "Pengaturan",
            "确定": "OK",
            "返回": "Kembali",
            "关闭": "Tutup",
            "清除": "Bersihkan",
            "提交": "Submit",
            "回答": "Jawaban",
            "发送": "Kirim",
            "消息": "Pesan",
            "会话": "Sesi",
            "连接": "Koneksi",
            "测试": "Uji",
            "配置": "Konfigurasi",
            "管理": "Manajemen",
            "供应商": "Provider",
            "统计": "Statistik",
            "用量": "Penggunaan",
            "费用": "Biaya",
            "明细": "Detail",
            "估算": "Estimasi",
            "模型": "Model",
            "选择": "Pilih",
            "列表": "Daftar",
            "版本": "Versi",
            "还原": "Pulihkan",
            "历史": "Riwayat",
            "通知": "Notifikasi",
            "任务": "Tugas",
            "清单": "Daftar",
            "队列": "Antrean",
            "排队": "Antre",
            "运行": "Berjalan",
            "进度": "Progres",
            "完成": "Selesai",
            "取消": "Batal",
            "中止": "Hentikan",
            "预览": "Pratinjau",
            "风格": "Gaya",
            "画面": "Gambar",
            "镜头": "Kamera",
            "环境": "Lingkungan",
            "提示词": "Prompt",
            "工作台": "Studio",
            "概览": "Ikhtisar",
            "首页": "Beranda",
            "未配置": "Belum dikonfigurasi",
            "已连接": "Terhubung",
            "已启用": "Diaktifkan",
            "已禁用": "Dinonaktifkan",
            "币种": "Mata uang",
            "输入": "Input",
            "输出": "Output",
            "默认": "Default",
            "手动": "Manual",
            "自动": "Otomatis",
            "全选": "Pilih semua",
            "取消全选": "Batal pilih semua",
            "搜索": "Cari",
            "隐藏": "Sembunyikan",
            "显示": "Tampilkan",
            "展开": "Buka",
            "收起": "Tutup",
            "全部": "Semua",
            "选项": "Opsi",
            "确认": "Konfirmasi",
            "确定": "OK",
            "提示": "Hint",
            "说明": "Penjelasan",
            "文档": "Dokumen",
            "技能": "Skill",
            "智能体": "Agen AI",
            "助手": "Asisten",
            "思考": "Berpikir",
            "过程": "Proses",
            "结果": "Hasil",
            "诊断": "Diagnostik",
            "冲突": "Konflik",
            "重复": "Duplikat",
            "重命名": "Ubah nama",
            "页面": "Halaman",
            "找到": "Ditemukan",
            "返回": "Kembali",
            "首页": "Beranda",
            "登录": "Login",
            "认证": "Autentikasi",
            "过期": "Kedaluwarsa",
            "重新": "Ulangi",
            "保存": "Simpan",
            "更改": "Perubahan",
            "未保存": "Belum disimpan",
            "标签页": "Tab",
            "标签": "Tag",
            "标记": "Tandai",
            "已读": "Sudah dibaca",
            "未读": "Belum dibaca",
            "新": "Baru",
            "通知": "Notifikasi",
            "中心": "Pusat",
            "区域": "Area",
            "面板": "Panel",
            "内容": "Konten",
            "文件": "File",
            "目录": "Direktori",
            "路径": "Path",
            "地址": "Alamat",
            "链接": "Link",
            "复制": "Salin",
            "粘贴": "Tempel",
            "下载": "Unduh",
            "上传": "Unggah",
            "草稿": "Draf",
            "剪映": "Jianying",
            "分镜图": "Storyboard",
            "设计图": "Desain",
            "参考图": "Referensi",
            "源文件": "File sumber",
            "剧本": "Skenario",
            "剧集": "Episode",
            "集": "Episode",
            "段": "Segmen",
            "片段": "Segmen",
            "分镜": "Storyboard",
            "场景": "Adegan",
            "角色": "Karakter",
            "线索": "Petunjuk",
            "道具": "Properti",
            "人物": "Karakter",
            "特征": "Fitur",
            "外貌": "Penampilan",
            "性格": "Kepribadian",
            "语言": "Bahasa",
            "镜头": "Kamera",
            "运动": "Gerakan",
            "氛围": "Atmosfer",
            "光线": "Cahaya",
            "构图": "Komposisi",
            "比例": "Rasio",
            "时长": "Durasi",
            "秒": "detik",
            "分钟": "menit",
            "小时": "jam",
            "天": "hari",
            "刚刚": "baru saja",
            "更新": "Perbarui",
            "新增": "Tambah",
            "删除": "Hapus",
            "生成": "Generate",
            "创建": "Buat",
            "打开": "Buka",
            "关闭": "Tutup",
            "撤销": "Urungkan",
            "重试": "Coba lagi",
            "刷新": "Segarkan",
            "同步": "Sinkron",
            "异步": "Asinkron",
            "加载": "Muat",
            "等待": "Tunggu",
            "解析": "Urai",
            "错误": "Error",
            "异常": "Eksepsi",
            "成功": "Berhasil",
            "失败": "Gagal",
            "完成": "Selesai",
            "就绪": "Siap",
            "激活": "Aktifkan",
            "禁用": "Nonaktifkan",
            "有效": "Valid",
            "无效": "Tidak valid",
            "必填": "Wajib",
            "可选": "Opsional",
            "高级": "Lanjutan",
            "配置": "Konfigurasi",
            "样式": "Gaya",
            "主题": "Tema",
            "颜色": "Warna",
            "字体": "Font",
            "对齐": "Alignment",
            "背景": "Latar belakang",
            "透明": "Transparan",
            "动画": "Animasi",
            "过渡": "Transisi",
            "渐显": "Fade in",
            "渐隐": "Fade out",
            "悬停": "Hover",
            "点击": "Klik",
            "拖拽": "Tarik",
            "释放": "Lepas",
            "滚动": "Scroll",
            "响应": "Respons",
            "宽度": "Lebar",
            "高度": "Tinggi",
            "大小": "Ukuran",
            "比例": "Rasio",
            "竖版": "Vertikal",
            "横版": "Horizontal",
            "正方形": "Kotak",
            "竖屏": "Layar vertikal",
            "全屏": "Layar penuh",
            "窗口": "Jendela",
            "弹窗": "Popup",
            "对话框": "Dialog",
            "侧边栏": "Sidebar",
            "页脚": "Footer",
            "顶栏": "Header",
            "导航": "Navigasi",
            "菜单": "Menu",
            "按钮": "Tombol",
            "输入框": "Input",
            "下拉框": "Dropdown",
            "复选框": "Checkbox",
            "单选框": "Radio",
            "滑块": "Slider",
            "开关": "Switch",
            "列表": "Daftar",
            "表格": "Tabel",
            "卡片": "Kartu",
            "图标": "Ikon",
            "文字": "Teks",
            "标题": "Judul",
            "描述": "Deskripsi",
            "备注": "Catatan",
            "详情": "Detail",
            "操作": "Aksi",
            "更多": "Lainnya",
            "返回": "Kembali",
            "取消": "Batal",
            "确定": "OK",
            "确认": "Konfirmasi",
            "提交": "Submit",
            "保存": "Simpan",
            "删除": "Hapus",
            "编辑": "Edit",
            "添加": "Tambah",
            "搜索": "Cari",
            "重置": "Reset",
            "清空": "Bersihkan",
            "全选": "Pilih semua",
            "反选": "Batal semua",
            "切换": "Ganti",
            "展开": "Buka",
            "收起": "Tutup",
            "刷新": "Segarkan",
            "加载": "Muat",
            "上传": "Unggah",
            "下载": "Unduh",
            "导出": "Ekspor",
            "导入": "Impor",
            "生成": "Generate",
            "开始": "Mulai",
            "停止": "Berhenti",
            "暂停": "Jeda",
            "继续": "Lanjut",
            "完成": "Selesai",
            "失败": "Gagal",
            "成功": "Berhasil",
            "警告": "Peringatan",
            "提示": "Informasi",
            "错误": "Error",
            "注意": "Perhatian",
            "重要": "Penting",
            "默认": "Default",
            "自定义": "Kustom",
            "官方": "Resmi",
            "系统": "Sistem",
            "设置": "Pengaturan",
            "中心": "Pusat",
            "管理": "Manajemen",
            "访问": "Akses",
            "凭证": "Kredensial",
            "供应商": "Provider",
            "模型": "Model",
            "用量": "Penggunaan",
            "统计": "Statistik",
            "费用": "Biaya",
            "明细": "Detail",
            "估算": "Estimasi",
            "余额": "Saldo",
            "记录": "Rekaman",
            "日志": "Log",
            "版本": "Versi",
            "历史": "Riwayat",
            "还原": "Pulihkan",
            "更新": "Perbarui",
            "详情": "Detail",
            "属性": "Atribut",
            "字段": "Field",
            "数据": "Data",
            "源": "Sumber",
            "文件": "File",
            "草稿": "Draf",
            "导出": "Ekspor",
            "导入": "Impor",
            "项目": "Proyek",
            "分镜": "Storyboard",
            "剧本": "Skenario",
            "场景": "Adegan",
            "角色": "Karakter",
            "线索": "Petunjuk",
            "剧情": "Plot",
            "概述": "Ikhtisar",
            "描述": "Deskripsi",
            "参考": "Referensi",
            "风格": "Gaya",
            "氛围": "Atmosfer",
            "环境": "Lingkungan",
            "画面": "Gambar",
            "视频": "Video",
            "音频": "Audio",
            "音效": "Efek suara",
            "台词": "Dialog",
            "配音": "Dubbing",
            "字幕": "Subtitel",
            "转场": "Transisi",
            "特效": "Efek",
            "滤镜": "Filter",
            "镜头": "Kamera",
            "机位": "Posisi kamera",
            "运镜": "Gerakan kamera",
            "时间轴": "Timeline",
            "帧": "Frame",
            "时长": "Durasi",
            "分辨率": "Resolusi",
            "质量": "Kualitas",
            "格式": "Format",
            "大小": "Ukuran",
            "速率": "Rate",
            "码率": "Bitrate",
            "采样率": "Sampling rate",
            "通道": "Saluran",
            "双通道": "Dual channel",
            "单通道": "Single channel",
            "渲染": "Render",
            "编码": "Encode",
            "解码": "Decode",
            "合成": "Komposisi",
            "导出": "Ekspor",
            "生成": "Generate",
            "创作": "Kreasi",
            "灵感": "Inspirasi",
            "智能": "Smart",
            "助": "Asisten",
            "思考": "Berpikir",
            "对话": "Dialog",
            "问题": "Pertanyaan",
            "答案": "Jawaban",
            "建议": "Saran",
            "提示": "Hint",
            "技能": "Skill",
            "能力": "Kemampuan",
            "工具": "Alat",
            "插件": "Plugin",
            "扩展": "Ekstensi",
            "集成": "Integrasi",
            "接口": "Antarmuka",
            "凭证": "Kredensial",
            "令牌": "Token",
            "密钥": "Key",
            "公钥": "Public key",
            "私钥": "Private key",
            "加密": "Enkripsi",
            "解密": "Dekripsi",
            "安全": "Keamanan",
            "隐私": "Privasi",
            "设置": "Pengaturan",
            "通用": "Umum",
            "显示": "Tampilan",
            "通知": "Notifikasi",
            "网络": "Jaringan",
            "存储": "Penyimpanan",
            "高级": "Lanjutan",
            "实验": "Eksperimen",
            "关于": "Tentang",
            "反馈": "Umpan balik",
            "帮助": "Bantuan",
            "文档": "Dokumen",
            "更新": "Update",
            "版本": "Versi",
            "许可": "Lisensi",
            "开源": "Open source",
            "社区": "Komunitas",
            "贡献": "Kontribusi",
            "开发": "Pengembangan",
            "调试": "Debug",
            "性能": "Performa",
            "稳定": "Stabil",
            "兼容": "Kompatibel",
            "优化": "Optimasi",
            "体验": "Pengalaman",
            "设计": "Desain",
            "简约": "Minimalis",
            "现代": "Modern",
            "专业": "Profesional",
            "自由": "Bebas",
            "强大": "Kuat",
            "简单": "Mudah",
            "快速": "Cepat",
            "高效": "Efisien",
            "实时": "Real-time",
            "智能": "Smart",
            "自动": "Otomatis",
            "批量": "Batch",
            "云": "Cloud",
            "本地": "Lokal",
            "同步": "Sinkron",
            "备份": "Cadangan",
            "还原": "Pulihkan",
            "安全": "Aman",
            "隐私": "Privat",
            "可靠": "Andal",
            "稳定": "Stabil",
            "流畅": "Lancar",
            "直观": "Intuitif",
            "友好": "Ramah",
            "美观": "Indah",
            "工作": "Kerja",
            "创作": "Kreativitas",
            "梦想": "Mimpi",
            "现实": "Realitas",
            "未来": "Masa depan",
            "智能体": "Agen AI",
            "机器人": "Robot",
            "伙伴": "Mitra",
            "协作": "Kolaborasi",
            "共创": "Kreasi bersama",
            "无限": "Tanpa batas",
            "可能": "Kemungkinan",
            "探索": "Eksplorasi",
            "发现": "Penemuan",
            "学习": "Pembelajaran",
            "成长": "Pertumbuhan",
            "成就": "Pencapaian",
            "分享": "Berbagi",
            "传播": "Penyebaran",
            "连接": "Koneksi",
            "互动": "Interaksi",
            "情感": "Emosi",
            "共鸣": "Resonansi",
            "故事": "Cerita",
            "传奇": "Legenda",
            "永恒": "Abadi",
            "经典": "Klasik",
            "艺术": "Seni",
            "科技": "Teknologi",
            "完美": "Sempurna",
            "平衡": "Keseimbangan",
            "极致": "Ekstrem",
            "简单": "Sederhana",
            "快乐": "Bahagia",
            "自由": "Bebas",
            "随心": "Sesuka hati",
            "所欲": "Keinginan",
            "创作": "Karya",
            "你的": "milik Anda",
            "我的": "milik saya",
            "我们的": "milik kita",
            "大家的": "milik semua",
            "全世界": "seluruh dunia",
            "每个人": "setiap orang",
            "都能": "bisa",
            "成为": "menjadi",
            "导演": "sutradara",
            "编剧": "penulis skenario",
            "艺术家": "seniman",
            "创作者": "kreator",
            "这就是": "Inilah",
            "ArcReel": "ArcReel",
            "开启": "Mulai",
            "一段": "sebuah",
            "奇妙": "ajaib",
            "旅程": "perjalanan",
            "吧": "!",
        }
        
        # Sort generic mapping keys by length descending as well
        sorted_generic_keys = sorted(generic_mapping.keys(), key=len, reverse=True)
        
        for key in sorted_generic_keys:
            # We use a regex for generic mapping to only replace whole Chinese character segments 
            # OR simple string replacement if it doesn't break things.
            # To be safe, we'll only do it if the character is still there.
            content = content.replace(key, generic_mapping[key])

        if content != original_content:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"Updated {file_path}")
        else:
            print(f"No changes in {file_path}")

